### ISSUE TITLE
Phantom of the temperature probe

### ISSUE THREAD

**Issue by Fraser86** [Rikkert-RS/VenusOS-TemperatureService#3] opened 2023-03-25 21:43 UTC
I recently got this running with a ds18b20 sensor. 
Fantastic and simple when you know how. 

I went further by removing my probe and adding three sensor together with a 4.7k resistor between the plus and the signal wire. Daisychained.
It works fine aswell. 

However the first cae which I named Kitchen is still present. With a temperature of -1c brrrr. 

I dont see why its there and how to remove. It from my device list
Anyone know whats going on

**Comment by Fraser86** [comment] 2023-03-25 21:44
(Cae) should be probe

**Comment by Fraser86** [comment] 2023-03-25 21:48
![Uploading 20230325_224604.jpg…]()

**Comment by Fraser86** [comment] 2023-03-25 21:49
![20230325_224559](https://user-images.githubusercontent.com/43178840/227743870-04631db8-a0fa-4648-a6da-c80be179ec27.jpg)

**Comment by Fraser86** [comment] 2023-03-25 21:50
![20230325_224604](https://user-images.githubusercontent.com/43178840/227743908-56a7c917-1a14-4d08-9bd9-5b1ef4d6b740.jpg)

**Comment by SirUli** [comment] 2023-03-26 07:26
I guess you have restarted the OS after you have changed the sensors, right? Theoretically the sensors which are no longer available should be possible to be deleted from the overview menu page.

**Comment by Fraser86** [comment] 2023-03-26 11:14
Yes. First thing i did was reset. Hoping it would clear. But stays. I dont see anywhere to delete it in overview menu. Also not in setup within that device

**Comment by Fraser86** [comment] 2023-03-26 11:15
Was thinking of solering that sensor into the daisy chain to see it is ID is recognised and temp is displayed. 

Question is still how to choose which temps are displayed and not.

**Comment by Fraser86** [comment] 2023-03-26 15:56
I reset my system several time. But it remains. 
In the device list there is sometimes the option to remove un-used devices but this is not present. I guess its because this probe is still seeing -1c. 

If i tap on the device (kitchen)
I see the setup and the device pull down menus. 
Setup gives me option to choose battery, fridge or generic. 
Device shows the attached image. 
No remove option visable to me 

![16798461621518331541222712865352](https://user-images.githubusercontent.com/43178840/227787839-e37058df-30e6-43c0-a915-df531b4bd17e.jpg)

**Comment by Rikkert-RS** [comment] 2023-03-27 23:39
Hello Fraser 86

I was able to reproduce your case today and will look for a solution tomorrow.

Best regards, Rikkert-RS

**Comment by Rikkert-RS** [comment] 2023-04-24 00:04
Hello Fraser86,

I just found time to solve the problem.

There was an error reading the temperature value. This is fixed in version 0.5
https://github.com/Rikkert-RS/VenusOS-TemperatureService/releases/tag/latest

If you remove a sensor, it will show as Disconnected after about 2 to 5 minutes. If you then do a reboot, the sensor is no longer there until you reconnect it

**Comment by Rikkert-RS** [comment] 2023-04-24 00:14
**Attention** completely forgotten. 
Please uninstall version v0.4 in the setup first before installing version 0.5 
because the GPIO PIN has been changed from **4 to 26**

**Comment by Fraser86** [comment] 2023-04-25 21:01
Ah. Thanks so much. 
So uninstall and reinstall. 
I have auto updates and v5 is running but i understand that i need to remove and reinstall. And need to move to gpio pin 26

Great that you fixed this. 
Awsome dude. 
Thanks alot

**Comment by Rikkert-RS** [comment] 2023-04-26 17:21
Hello Fraser86,

Yes you have to uninstall version 0.4 first because otherwise the gpio pin can't be changed properly from 4 to 26. The reason why I changed the pin is that I installed a can hat for a canbus battery and that unfortunately collides. Pin 4 could also cause problems for other people and other raspberry shields.

Maybe in the future i can make the pin configurable, currently you have to change the pin in your hardware setup.

**Comment by Rikkert-RS** [comment] 2023-04-26 17:51
If you still have problems, just write again

**Comment by Fraser86** [comment] 2023-05-02 13:51
I am having problems to get this to work. 
I have moved over to a test pi. I have this so i dont end up without my solar monitor. 
I playing with the relays and temps. 
But i have moved to gpio26 and 5v and ground. But the temperatures are not showing. 
Firmware was 3.0. Now running 2.94 to see if that work. 
Rebooted many times. But temperature reading not showing

**Comment by Fraser86** [comment] 2023-05-02 13:53
![16830355275363644623887111232402](https://user-images.githubusercontent.com/43178840/235687170-a4a19f07-fd98-4758-9663-4f0255ec22fb.jpg)

**Comment by Fraser86** [comment] 2023-05-02 13:53
![16830356016453323035635864737511](https://user-images.githubusercontent.com/43178840/235687385-8fbd755e-dc93-48d5-a920-1568be2dc92f.jpg)
Only cpu showing

**Comment by Rikkert-RS** [comment] 2023-05-02 16:44
OK, that's not so good, but I think I can help you. For this I need some more information.
First: An test-Pi is a good solution ;)

1. Have you installed RpiGpioSetup? 
If yes please uninstall and check again. The reason for this is that it is very difficult to always find the right free GPIO that does     not collide with other things.
If it works then you just have to create a custom GPIO list for RpiGpioSetup that's not difficult

3. What kind of sensor have you now installed?

4. if it is a DS18B20 how it is connected?
Don't forget the pull-up resistor
Example image:
![grafik](https://user-images.githubusercontent.com/96136114/235730528-4bf97b7b-1e36-464e-9063-8273508c8406.png)

5. Can you access your Pi via SSH to read a few some log files?
Run this on a connected shell:
`tail -n +1 /data/log/VenusOS-TemperatureService/current | tai64nlocal`
`tail -n +1 /u-boot/config.txt`

**Comment by Rikkert-RS** [comment] 2023-05-02 18:53
Hello, I have found something after all. 
Because you have auto update active, most likely the pin was not changed from 4 to 26 in the config. Here is a solution without you have to do something via SSH. 
Go to the Packagemanager and change the tag from "latest" to "v0.4" -> downlaod -> install. 
Then unistall the v.04
After that change the tag again to latest -> download -> install.

then i hope pin26 is running. If not i need the logs

![grafik](https://user-images.githubusercontent.com/96136114/235758377-e2e6dca6-1c4d-4204-8ffe-5d13dad2bc62.png)

**Comment by Rikkert-RS** [comment] 2023-05-21 18:22
no answer anymore problem is probably solved

**Closed as completed by Rikkert-RS** 2023-05-21 18:22 UTC

**Comment by Fraser86** [comment] 2023-05-23 11:27
No. Just had no time. Busy working alot and small child at home. But i will let you know when i find some time to do this.
